Info for virtual env install. Years 2017 to 2022 in output.
USEPA/USEEIO pull request #34
Opened 2024-05-20 17:37 UTC by ModelEarth

2019 was already in output and did not change when rerunning.

2024-05-22 14:57 UTC, bl-young requested changes
as we discussed on email, let's re-do this PR without the data for 2017, 2018, 2020-2022 committed (probably no need to commit the 2019 results either since no changes were made outside of rounding).

so really the only thing that needs to be added is the updated readme

2024-05-22 14:57 UTC, bl-young commented on import_factors_exio/README.md
> +	pip install git+https://github.com/USEPA/esupy.git#egg=esupy
esupy is a requirement of fedelemflowlist, so no need to install it separately

2024-05-22 14:57 UTC, bl-young commented on import_factors_exio/README.md
> +[Available models](https://dmap-data-commons-ord.s3.amazonaws.com/index.html?prefix=#USEEIO-State/) - All states 2012-2020.
These state models aren't related to this particular effort so this line should be removed

2024-05-22 14:57 UTC, bl-young commented on import_factors_exio/README.md
> +Now run the app. Before running, you can change the year range at the top of generate_import_factors.py. If the year is not yet available, the other years will still be generated. (2023 was not yet a
I will likely adjust this text to specifically state what years have been tested.

2024-05-22 14:59 UTC, bl-young commented on import_factors_exio/README.md
> +	pip install pathlib
pathlib is a core python package so does not need to be installed with pip.

I'm also fine with supplying an env file here instead

2024-05-23 11:55 UTC, ModelEarth commented
Reissuing with just Readme

2024-05-23 11:55 UTC, closed without merging